x-backend: &backend
  image: django-example:latest
  build: .
  env_file: .env
  environment:
    DB_HOST: db
    DB_PORT: 5432
  depends_on:
    db:
      condition: service_healthy

services:
  db:
    image: postgres:17.1-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 10

  migrations:
    <<: *backend
    command: python manage.py migrate
    volumes:
      - .:/app

  static_collector:
    <<: *backend
    command: python manage.py collectstatic -c --no-input
    volumes:
      - static:/app/static

  backend:
    <<: *backend
    command: gunicorn config.wsgi --workers 4 --access-logfile - --error-logfile - -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/app
    healthcheck:
      test: python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"
      interval: 10s
      timeout: 2s
      start_interval: 2s
      start_period: 5s
      retries: 5

  nginx:
    image: nginx:1.28-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      static_collector:
        condition: service_completed_successfully
      backend:
        condition: service_healthy

volumes:
  pg_data:
  static: