name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@v7
        with:
          python-version-file: 'pyproject.toml'
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run linters checks
        run: poetry run make check

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      SECRET_KEY: test
      DEBUG: true
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
    steps:
      - uses: actions/checkout@v7
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@v7
        with:
          python-version-file: 'pyproject.toml'
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run linters checks
        run: |
          poetry run make test
          poetry run coverage xml
      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
